queue_rules:
  - name: default
    queue_conditions:
      - check-success = tests
      - check-success = contract-tests
      - check-success = linting
      - check-success = docker-health-check
    merge_conditions:
      - check-success = tests
      - check-success = contract-tests
      - check-success = linting
      - check-success = docker-health-check
    merge_method: squash
    batch_size: 3
    batch_max_wait_time: 5 minutes

pull_request_rules:
  - name: add to merge queue when CI is green
    conditions:
      - base = main
      - check-success = tests
      - check-success = contract-tests
      - check-success = linting
      - check-success = docker-health-check
    actions:
      queue:
        name: default
