version: '3.8'
services:
  aimagain:
    image: ghcr.io/willthefirst/aimagain:latest
    container_name: aimagain-app
    restart: unless-stopped
    ports:
      - '8000:8000'
    volumes:
      - ./data:/app/data
    env_file:
      - config/.env
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
