[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "chat-app"
version = "0.1.0"
description = "A simple chat application."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    # Core runtime dependencies
    "fastapi",
    "uvicorn[standard]",
    "sqlalchemy",
    "alembic",
    "python-dotenv",
    "async-lru",
    "Jinja2",
    "selectolax",
    "fastapi-users[sqlalchemy]",
    "aiosqlite",
    "pydantic-settings",
    "asyncstdlib",
]

[project.optional-dependencies]
# Development dependencies
dev = [
    "livereload",  # For client-side hot reloading in development
    "pathspec",   # For gitignore support in title case checker
]

# Testing dependencies
test = [
    "pytest",
    "pytest-asyncio",
    "pytest-playwright-asyncio",
    "httpx",  # For API testing
    "pact-python",  # For contract testing
]

# Code quality and formatting
lint = [
    "black",
    "isort",
    "autoflake",
    "pre-commit",
]

# All development dependencies combined
all = [
    "chat-app[dev,test,lint]",
]

[project.scripts]
aim = "scripts.dev_cli:main"

# Tool configurations
[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 88

[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = "-v"
testpaths = ["tests"]
markers = [
    "api: API tests",
    "unit: Unit tests",
    "integration: Integration tests",
    "consumer: Consumer contract tests",
    "provider: Provider contract tests",
    "slow: Tests that take more than 5 seconds",
]
filterwarnings = [
    "ignore::DeprecationWarning:starlette",
    "ignore::PendingDeprecationWarning:starlette",
    "ignore:.*will be deprecated Pact Python v3:PendingDeprecationWarning",
]

[tool.title-case-check]
ignore_files = [
    "*.log", "*.tmp", ".git/**", "venv/**", "node_modules/**",
    "build/**", "dist/**", "__pycache__/**"
]
always_capitalize = [
    "API", "APIs", "URL", "URLs", "HTTP", "HTTPS", "JSON", "XML", "HTML", "CSS", "JS",
    "SQL", "REST", "RESTful", "FastAPI", "SQLAlchemy", "Jinja2", "pytest", "GitHub",
    "OAuth", "JWT", "UUID", "UUIDs", "CRUD", "TDD", "LLM", "LLMs", "AI", "MVP",
    "PostgreSQL", "SQLite", "Docker", "Python", "JavaScript", "TypeScript",
]
