[build]
builder = "dockerfile"

[deploy]
preDeployCommand = "alembic upgrade head"
startCommand = "uvicorn app.main:app --host 0.0.0.0"
restartPolicyType = "on_failure"

[volumes]
# Mount persistent volume for SQLite database
data = "/app/data"
