"""Helpers for provider verification tests.

`verify_pair(pair, provider_server)` runs the Pact `Verifier` for a single
`ContractPair` against a running provider server. Provider verification
tests under `tests/provider/` parametrize over `pairs_for_provider(name)`
and call this helper — replacing the per-pair `BaseProviderVerification`
subclasses that used to live in each `test_*_verification.py` file.

`create_provider_test_decorator(dependency_config, test_id)` is the
parametrize-on-`provider_server` decorator that wires a module-scoped
provider server with the right handler mocks. Unchanged interface from
before the manifest landed.
"""

import logging
import os
from typing import TYPE_CHECKING, Any, Dict

import pytest
from pact import Verifier
from yarl import URL

from tests.test_contract.infrastructure.config import (
    PROVIDER_STATE_SETUP_ENDPOINT_PATH,
)
from tests.test_contract.tests.shared.helpers import PACT_DIR, PACT_LOG_DIR

if TYPE_CHECKING:
    from tests.test_contract.manifest import ContractPair

log = logging.getLogger(__name__)


def verify_pact_and_handle_result(success: int, logs_dict: dict, pact_name: str):
    """Helper to handle pact verification results."""
    if success != 0:
        log.error(f"{pact_name} Pact verification failed. Logs:")
        try:
            import json

            print(json.dumps(logs_dict, indent=4))
        except ImportError:
            print(logs_dict)
        except Exception as e:
            log.error(f"Error printing pact logs: {e}")
            print(logs_dict)
        pytest.fail(
            f"{pact_name} Pact verification failed (exit code: {success}). Check logs."
        )


def _pact_file_path(pair: "ContractPair") -> str:
    return os.path.join(PACT_DIR, f"{pair.consumer_name}-{pair.provider_name}.json")


def verify_pair(pair: "ContractPair", provider_server: URL) -> None:
    """Verify the pact for `pair` against the running `provider_server`.

    Fails the test with a descriptive message if the pact JSON file
    isn't on disk (which happens when the provider verification runs
    in isolation without the consumer side first generating the pact).
    """
    pact_file = _pact_file_path(pair)
    if not os.path.exists(pact_file):
        pytest.fail(
            f"Pact file not found: {pact_file}.\n"
            "Pact files are generated by the consumer tests and wiped at "
            "the start of every session by `clean_pact_dir_before_session`. "
            "Run the consumer + provider together:\n"
            "    dev test tests/test_contract\n"
            "Running only a provider file in isolation will always fail "
            "with this error."
        )

    verifier = Verifier(
        provider=pair.provider_name,
        provider_base_url=str(provider_server),
        # Built from the running server's (ephemeral) URL, not a fixed
        # constant, so the verifier posts states to the right port.
        provider_states_setup_url=str(
            provider_server / PROVIDER_STATE_SETUP_ENDPOINT_PATH
        ),
    )

    success, logs_dict = verifier.verify_pacts(pact_file, log_dir=PACT_LOG_DIR)

    verify_pact_and_handle_result(success, logs_dict, f"{pair.provider_name.title()}")


def create_provider_test_decorator(dependency_config: Dict[str, Any], test_id: str):
    """Create a parametrize decorator that wires a module-scoped
    provider server with the given handler-mocks dict."""
    return pytest.mark.parametrize(
        "provider_server",
        [dependency_config],
        indirect=True,
        scope="module",
        ids=[test_id],
    )
