"""add affirming_identities to clinicians and referral_details

Symmetric affirming-identity vocabulary (#1358 PR-a). Adds a JSON-list
column to two tables:

- ``clinicians.affirming_identities`` — person-level claim (who the
  clinician *is*; lives directly on the person, like credentials, not on
  a per-affiliation row).
- ``referral_details.affirming_identities`` — referrer-side request
  constraint (matches the provider claim above).

Both columns are NOT NULL with a server-side default of ``'[]'``; the
SQLite/Postgres JSON column stores an empty array for every existing
row at upgrade time, so there is no separate backfill step. No CHECK
constraint on JSON array members — the vocabulary
(``AFFIRMING_IDENTITIES``) is enforced on the wire by Pydantic, mirroring
the pattern used by ``services`` / ``age_groups`` / ``in_network_carriers``.

Downgrade drops both columns; data loss is the expected outcome of
reverting an additive vocabulary column.

Revision ID: 2621a96f2e46
Revises: 9501786659b3
Create Date: 2026-06-10 18:54:13.794209

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2621a96f2e46"
down_revision: Union[str, None] = "9501786659b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clinicians",
        sa.Column(
            "affirming_identities",
            sa.JSON(),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
    )
    op.add_column(
        "referral_details",
        sa.Column(
            "affirming_identities",
            sa.JSON(),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("referral_details", "affirming_identities")
    op.drop_column("clinicians", "affirming_identities")
    # ### end Alembic commands ###
