"""add org_representations table (Phase 1c)

Revision ID: 386c191fb144
Revises: 76b43539731b
Create Date: 2026-05-31 13:27:16.723145

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "386c191fb144"
down_revision: Union[str, None] = "76b43539731b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "org_representations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("authority_method", sa.Text(), nullable=False),
        sa.Column(
            "authority_status", sa.Text(), server_default="pending", nullable=False
        ),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("archived_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "authority_method IN ('authorized_official', 'domain_email', 'rep_approval', 'admin_review')",
            name="ck_org_representations_authority_method",
        ),
        sa.CheckConstraint(
            "authority_status IN ('pending', 'verified', 'rejected')",
            name="ck_org_representations_authority_status",
        ),
        sa.CheckConstraint(
            "role IN ('coordinator', 'admin', 'owner')",
            name="ck_org_representations_role",
        ),
        sa.ForeignKeyConstraint(["approved_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "org_id", name="uq_org_representations_user_org"
        ),
    )
    op.create_index(
        op.f("ix_org_representations_org_id"),
        "org_representations",
        ["org_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_org_representations_user_id"),
        "org_representations",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_org_representations_user_id"), table_name="org_representations"
    )
    op.drop_index(
        op.f("ix_org_representations_org_id"), table_name="org_representations"
    )
    op.drop_table("org_representations")
    # ### end Alembic commands ###
