"""opening gains profile fields; affiliation slims to steady-state context

Reverses the #1358 split for the per-announcement dimensions: the
clinician-opening post becomes self-describing while the affiliation
becomes thin steady-state context.

``opening_details`` gains ``session_format`` / ``services`` /
``services_other_text`` / ``age_groups`` / ``genders`` / ``cost`` (the
announcement profile; ``services`` on the ``ReferralService`` vocabulary).

``clinician_affiliations`` drops the columns that moved onto the opening
(``services`` / ``settings`` / ``modalities`` / ``age_groups`` /
``genders`` / ``cost`` / ``in_person_sessions`` / ``virtual_sessions``)
plus ``location_zip`` (the affiliation now models a city/area + state like
a referral, no ZIP). Steady-state context — location, insurance posture,
website / referral_instructions, the accepting-new-patients cache —
stays. No backfill: the dropped values are discarded (the opening starts
with empty profile lists).

Revision ID: 39bfbf922221
Revises: 4d1e8249729d
Create Date: 2026-06-21 08:35:05.886682

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39bfbf922221"
down_revision: Union[str, None] = "4d1e8249729d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # `in_person_sessions` / `virtual_sessions` carry named CHECK
    # constraints; SQLite can't `DROP COLUMN` a CHECK-referenced column
    # in place. Drop each CHECK then its column inside one
    # `batch_alter_table` (one table rewrite) — same pattern as
    # `8c1f8f40228e`. `location_state`'s CHECK survives untouched.
    with op.batch_alter_table("clinician_affiliations") as batch_op:
        batch_op.drop_constraint(
            "ck_clinician_affiliations_in_person_sessions", type_="check"
        )
        batch_op.drop_column("in_person_sessions")
        batch_op.drop_constraint(
            "ck_clinician_affiliations_virtual_sessions", type_="check"
        )
        batch_op.drop_column("virtual_sessions")
        batch_op.drop_column("modalities")
        batch_op.drop_column("services")
        batch_op.drop_column("age_groups")
        batch_op.drop_column("genders")
        batch_op.drop_column("cost")
        batch_op.drop_column("location_zip")
        batch_op.drop_column("settings")
    op.add_column(
        "opening_details",
        sa.Column(
            "session_format", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "opening_details",
        sa.Column(
            "services", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "opening_details", sa.Column("services_other_text", sa.Text(), nullable=True)
    )
    op.add_column(
        "opening_details",
        sa.Column(
            "age_groups", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "opening_details",
        sa.Column("genders", sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    )
    op.add_column("opening_details", sa.Column("cost", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Re-adds the affiliation columns and restores the two session CHECK
    constraints (via `create_check_constraint`) so a subsequent upgrade
    can drop them again — the up/down/up roundtrip stays idempotent.
    """
    op.drop_column("opening_details", "cost")
    op.drop_column("opening_details", "genders")
    op.drop_column("opening_details", "age_groups")
    op.drop_column("opening_details", "services_other_text")
    op.drop_column("opening_details", "services")
    op.drop_column("opening_details", "session_format")
    with op.batch_alter_table("clinician_affiliations") as batch_op:
        batch_op.add_column(sa.Column("virtual_sessions", sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column("in_person_sessions", sa.TEXT(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "settings",
                sqlite.JSON(),
                server_default=sa.text("'[]'"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("location_zip", sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column("cost", sa.TEXT(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "genders", sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "age_groups",
                sqlite.JSON(),
                server_default=sa.text("'[]'"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "services",
                sqlite.JSON(),
                server_default=sa.text("'[]'"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "modalities",
                sqlite.JSON(),
                server_default=sa.text("'[]'"),
                nullable=False,
            )
        )
        batch_op.create_check_constraint(
            "ck_clinician_affiliations_in_person_sessions",
            "in_person_sessions IN ('yes', 'no')",
        )
        batch_op.create_check_constraint(
            "ck_clinician_affiliations_virtual_sessions",
            "virtual_sessions IN ('yes', 'no')",
        )
