"""initial schema

Revision ID: 43c694311395
Revises:
Create Date: 2026-06-07 21:48:22.309165

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43c694311395"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_log",
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("resource_type", sa.Text(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clinicians",
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("npi", sa.Text(), nullable=True),
        sa.Column("first_name", sa.Text(), nullable=False),
        sa.Column("last_name", sa.Text(), nullable=False),
        sa.Column("npi_match_status", sa.Text(), server_default="none", nullable=False),
        sa.Column("npi_verified_at", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "clinician_verified", sa.Boolean(), server_default="0", nullable=False
        ),
        sa.Column("verified_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("ever_verified_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "npi IS NULL OR (length(npi) = 10 AND npi GLOB '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')",
            name="ck_clinicians_npi_format",
        ),
        sa.CheckConstraint(
            "npi_match_status IN ('none', 'pending', 'matched', 'mismatch')",
            name="ck_clinicians_npi_match_status",
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("npi", sa.Text(), nullable=True),
        sa.Column("npi_match_status", sa.Text(), server_default="none", nullable=False),
        sa.Column("org_verified", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("verified_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("authorized_official_name", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "npi IS NULL OR (length(npi) = 10 AND npi GLOB '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')",
            name="ck_organizations_npi_format",
        ),
        sa.CheckConstraint(
            "npi_match_status IN ('none', 'pending', 'matched', 'mismatch')",
            name="ck_organizations_npi_match_status",
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "posts",
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('referral', 'clinician_opening', 'program_intake')",
            name="ck_posts_kind",
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clinician_affiliations",
        sa.Column("clinician_id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("in_person_sessions", sa.Text(), nullable=False),
        sa.Column("virtual_sessions", sa.Text(), nullable=False),
        sa.Column(
            "accepts_out_of_network",
            sa.Boolean(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column(
            "in_network_carriers",
            sa.JSON(),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "sliding_scale", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("cost", sa.Text(), nullable=True),
        sa.Column("location_city", sa.Text(), nullable=True),
        sa.Column("location_state", sa.Text(), nullable=True),
        sa.Column("location_zip", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "in_person_sessions IN ('yes', 'no', 'please_contact')",
            name="ck_clinician_affiliations_in_person_sessions",
        ),
        sa.CheckConstraint(
            "location_state IN ('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY')",
            name="ck_clinician_affiliations_location_state",
        ),
        sa.CheckConstraint(
            "virtual_sessions IN ('yes', 'no', 'please_contact')",
            name="ck_clinician_affiliations_virtual_sessions",
        ),
        sa.ForeignKeyConstraint(
            ["clinician_id"], ["clinicians.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clinician_certifications",
        sa.Column("clinician_id", sa.Uuid(), nullable=False),
        sa.Column("certification_type", sa.Text(), nullable=False),
        sa.Column("certifying_body", sa.Text(), nullable=False),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "certification_type IN ('emdr', 'dbt', 'cbt', 'gottman_1', 'gottman_2', 'gottman_3', 'cpr', 'ccatp', 'other')",
            name="ck_clinician_certifications_certification_type",
        ),
        sa.ForeignKeyConstraint(
            ["clinician_id"], ["clinicians.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clinician_educations",
        sa.Column("clinician_id", sa.Uuid(), nullable=False),
        sa.Column("education_type", sa.Text(), nullable=False),
        sa.Column("institution", sa.Text(), nullable=False),
        sa.Column("month_completed", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "education_type IN ('ba_bs', 'ma_ms', 'msw', 'phd', 'psyd', 'md', 'do', 'edd', 'other')",
            name="ck_clinician_educations_education_type",
        ),
        sa.ForeignKeyConstraint(
            ["clinician_id"], ["clinicians.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clinician_licensures",
        sa.Column("clinician_id", sa.Uuid(), nullable=False),
        sa.Column("license_type", sa.Text(), nullable=False),
        sa.Column("license_number", sa.Text(), nullable=False),
        sa.Column("issuing_state", sa.Text(), nullable=False),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("attested_active", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("attested_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "issuing_state IN ('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY')",
            name="ck_clinician_licensures_issuing_state",
        ),
        sa.CheckConstraint(
            "license_type IN ('lcsw', 'lpc', 'lmft', 'lmhc', 'lcpc', 'psyd', 'phd', 'md', 'do', 'np', 'pmhnp', 'other')",
            name="ck_clinician_licensures_license_type",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'expired', 'pending')",
            name="ck_clinician_licensures_status",
        ),
        sa.ForeignKeyConstraint(
            ["clinician_id"], ["clinicians.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "org_representations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("authority_method", sa.Text(), nullable=False),
        sa.Column(
            "authority_status", sa.Text(), server_default="pending", nullable=False
        ),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("archived_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "authority_method IN ('authorized_official', 'domain_email', 'rep_approval', 'admin_review')",
            name="ck_org_representations_authority_method",
        ),
        sa.CheckConstraint(
            "authority_status IN ('pending', 'verified', 'rejected')",
            name="ck_org_representations_authority_status",
        ),
        sa.CheckConstraint(
            "role IN ('coordinator', 'admin', 'owner')",
            name="ck_org_representations_role",
        ),
        sa.ForeignKeyConstraint(["approved_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "org_id", name="uq_org_representations_user_org"
        ),
    )
    op.create_index(
        op.f("ix_org_representations_org_id"),
        "org_representations",
        ["org_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_org_representations_user_id"),
        "org_representations",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "programs",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("state_preference", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "accepting_referrals",
            sa.Boolean(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state_preference IN ('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY')",
            name="ck_programs_state_preference",
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_favorites",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("clinician_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["clinician_id"], ["clinicians.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "clinician_id", name="uq_user_favorites_user_clinician"
        ),
    )
    op.create_index(
        "ix_user_favorites_user_id_created_at",
        "user_favorites",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "verifications",
        sa.Column(
            "subject_type", sa.Text(), server_default="clinician", nullable=False
        ),
        sa.Column("clinician_id", sa.Uuid(), nullable=True),
        sa.Column("org_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "event_type", sa.Text(), server_default="npi_resolved", nullable=False
        ),
        sa.Column("flags", sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
        sa.Column("nppes_result", sa.JSON(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.Column(
            "oig_match", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("name_match_score", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(subject_type = 'clinician' AND clinician_id IS NOT NULL AND org_id IS NULL) OR (subject_type = 'organization' AND clinician_id IS NULL AND org_id IS NOT NULL)",
            name="ck_verifications_subject_shape",
        ),
        sa.CheckConstraint(
            "event_type IN ('npi_submitted', 'npi_resolved', 'license_attested', 'license_expired', 'authority_proven', 'authority_revoked', 'role_set', 'admin_verify', 'admin_suspend', 'email_confirmed')",
            name="ck_verifications_event_type",
        ),
        sa.CheckConstraint(
            "status IN ('verified', 'needs_review', 'failed')",
            name="ck_verifications_status",
        ),
        sa.CheckConstraint(
            "subject_type IN ('clinician', 'organization')",
            name="ck_verifications_subject_type",
        ),
        sa.ForeignKeyConstraint(
            ["clinician_id"], ["clinicians.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verifications_clinician_id"),
        "verifications",
        ["clinician_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verifications_org_id"), "verifications", ["org_id"], unique=False
    )
    op.create_table(
        "intake_details",
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column(
            "desired_times", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column("schedule_text", sa.Text(), nullable=True),
        sa.Column(
            "services", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column(
            "settings", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column("treatment_modality", sa.Text(), nullable=True),
        sa.Column(
            "modalities", sa.JSON(), server_default=sa.text("'[]'"), nullable=True
        ),
        sa.Column(
            "age_groups", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column(
            "languages", sa.JSON(), server_default=sa.text("'[\"en\"]'"), nullable=False
        ),
        sa.Column("genders", sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("referral_instructions", sa.Text(), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["program_id"], ["programs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("post_id"),
    )
    op.create_table(
        "opening_details",
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("clinician_id", sa.Uuid(), nullable=False),
        sa.Column(
            "desired_times", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column("schedule_text", sa.Text(), nullable=True),
        sa.Column(
            "services", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column(
            "settings", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column("treatment_modality", sa.Text(), nullable=True),
        sa.Column(
            "modalities", sa.JSON(), server_default=sa.text("'[]'"), nullable=True
        ),
        sa.Column(
            "age_groups", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column(
            "languages", sa.JSON(), server_default=sa.text("'[\"en\"]'"), nullable=False
        ),
        sa.Column("genders", sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("referral_instructions", sa.Text(), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("clinician_affiliation_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["clinician_affiliation_id"],
            ["clinician_affiliations.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["clinician_id"], ["clinicians.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("post_id"),
    )
    op.create_table(
        "referral_details",
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("location_in_person", sa.Text(), nullable=False),
        sa.Column("location_virtual", sa.Text(), nullable=False),
        sa.Column(
            "desired_times", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column(
            "age_groups", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column(
            "languages", sa.JSON(), server_default=sa.text("'[\"en\"]'"), nullable=False
        ),
        sa.Column(
            "gender",
            sa.Text(),
            server_default=sa.text("'prefer_not_to_say'"),
            nullable=False,
        ),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "services", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column("treatment_modality", sa.Text(), nullable=True),
        sa.Column(
            "modalities", sa.JSON(), server_default=sa.text("'[]'"), nullable=True
        ),
        sa.Column(
            "network_preference",
            sa.Text(),
            server_default=sa.text("'no_preference'"),
            nullable=False,
        ),
        sa.Column("insurance_carrier", sa.Text(), nullable=True),
        sa.Column("referring_clinician_id", sa.Uuid(), nullable=True),
        sa.Column("clinician_affiliation_id", sa.Uuid(), nullable=True),
        sa.Column("location_city", sa.Text(), nullable=False),
        sa.Column("location_state", sa.Text(), nullable=False),
        sa.Column("location_zip", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "gender IN ('female', 'male', 'non_binary', 'trans_female', 'trans_male', 'gender_diverse', 'prefer_not_to_say')",
            name="ck_referral_details_gender",
        ),
        sa.CheckConstraint(
            "insurance_carrier IN ('aetna', 'anthem_bcbs', 'cigna', 'kaiser', 'magellan', 'medicare', 'medicaid', 'optum', 'tricare', 'united_healthcare', 'other')",
            name="ck_referral_details_insurance_carrier",
        ),
        sa.CheckConstraint(
            "location_in_person IN ('yes', 'no', 'please_contact')",
            name="ck_referral_details_location_in_person",
        ),
        sa.CheckConstraint(
            "location_state IN ('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY')",
            name="ck_referral_details_location_state",
        ),
        sa.CheckConstraint(
            "location_virtual IN ('yes', 'no', 'please_contact')",
            name="ck_referral_details_location_virtual",
        ),
        sa.CheckConstraint(
            "network_preference IN ('in_network_required', 'in_network_preferred', 'no_preference')",
            name="ck_referral_details_network_preference",
        ),
        sa.ForeignKeyConstraint(
            ["clinician_affiliation_id"],
            ["clinician_affiliations.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["referring_clinician_id"], ["clinicians.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("post_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("referral_details")
    op.drop_table("opening_details")
    op.drop_table("intake_details")
    op.drop_index(op.f("ix_verifications_org_id"), table_name="verifications")
    op.drop_index(op.f("ix_verifications_clinician_id"), table_name="verifications")
    op.drop_table("verifications")
    op.drop_index("ix_user_favorites_user_id_created_at", table_name="user_favorites")
    op.drop_table("user_favorites")
    op.drop_table("programs")
    op.drop_index(
        op.f("ix_org_representations_user_id"), table_name="org_representations"
    )
    op.drop_index(
        op.f("ix_org_representations_org_id"), table_name="org_representations"
    )
    op.drop_table("org_representations")
    op.drop_table("clinician_licensures")
    op.drop_table("clinician_educations")
    op.drop_table("clinician_certifications")
    op.drop_table("clinician_affiliations")
    op.drop_table("posts")
    op.drop_table("organizations")
    op.drop_table("clinicians")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
