"""drop subject + treatment_modality from opening/intake details

Sheds the last two per-announcement override columns from the thin
``opening_details`` / ``intake_details`` rows, aligning them with the
referral model: the headline is now derived (org / program name, never a
poster-set ``subject``) and modality reads from the linked affiliation /
program's structured ``modalities`` list (never a free-text
``treatment_modality`` override). Both columns are plain nullable TEXT
with no CHECK, so a plain ``drop_column`` suffices on SQLite.

Downgrade re-adds the columns as nullable TEXT; the dropped values are
not recoverable (the application no longer reads or writes them).

Revision ID: 4d1e8249729d
Revises: e7b3d2c9a4f1
Create Date: 2026-06-20 22:14:48.690223

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d1e8249729d"
down_revision: Union[str, None] = "e7b3d2c9a4f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("intake_details", "subject")
    op.drop_column("intake_details", "treatment_modality")
    op.drop_column("opening_details", "subject")
    op.drop_column("opening_details", "treatment_modality")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "opening_details", sa.Column("treatment_modality", sa.TEXT(), nullable=True)
    )
    op.add_column("opening_details", sa.Column("subject", sa.TEXT(), nullable=True))
    op.add_column(
        "intake_details", sa.Column("treatment_modality", sa.TEXT(), nullable=True)
    )
    op.add_column("intake_details", sa.Column("subject", sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
