"""drop old steady-state cols from opening_details / intake_details (PR-f sub-3)

Third of three migrations for the #1358 PR-f normalization:
``OpeningDetail`` ↔ ``ClinicianAffiliation`` and ``IntakeDetail`` ↔
``Program``. Reads were flipped onto the new homes in sub-PR 2 with a
dual-write safety net; this migration removes that net by dropping the
per-announcement columns from ``opening_details`` and ``intake_details``.
After this migration the detail rows are thin — they carry only the
announcement core (``desired_times`` / ``schedule_text`` / ``subject`` /
``description`` / ``treatment_modality``) plus their context FKs.

Columns removed from both tables:

  - ``services``, ``settings``, ``modalities``, ``age_groups``,
    ``genders``, ``website``, ``referral_instructions``, ``languages``

The steady-state copies on ``clinician_affiliations`` /
``clinicians.languages`` / ``programs`` already carry the canonical
values (backfilled by ``f3c128112fa7`` and kept in lockstep through the
sub-PR 2 dual-write window).

Downgrade re-adds the columns with their original defaults. Any rows
that lived only on the steady-state home after the drop have no value
to replay; downgrade therefore leaves the re-added columns at their
column defaults — the application reads from the steady-state home,
not from these columns, after sub-PR 2.

Revision ID: 57161384b6db
Revises: f3c128112fa7
Create Date: 2026-06-10 22:10:21.565835

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57161384b6db"
down_revision: Union[str, None] = "7092114bc0c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("intake_details", "modalities")
    op.drop_column("intake_details", "referral_instructions")
    op.drop_column("intake_details", "genders")
    op.drop_column("intake_details", "languages")
    op.drop_column("intake_details", "age_groups")
    op.drop_column("intake_details", "services")
    op.drop_column("intake_details", "settings")
    op.drop_column("intake_details", "website")
    op.drop_column("opening_details", "modalities")
    op.drop_column("opening_details", "referral_instructions")
    op.drop_column("opening_details", "genders")
    op.drop_column("opening_details", "languages")
    op.drop_column("opening_details", "age_groups")
    op.drop_column("opening_details", "services")
    op.drop_column("opening_details", "settings")
    op.drop_column("opening_details", "website")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("opening_details", sa.Column("website", sa.TEXT(), nullable=True))
    op.add_column(
        "opening_details",
        sa.Column(
            "settings", sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "opening_details",
        sa.Column(
            "services", sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "opening_details",
        sa.Column(
            "age_groups", sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "opening_details",
        sa.Column(
            "languages",
            sqlite.JSON(),
            server_default=sa.text("'[\"en\"]'"),
            nullable=False,
        ),
    )
    op.add_column(
        "opening_details",
        sa.Column(
            "genders", sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "opening_details", sa.Column("referral_instructions", sa.TEXT(), nullable=True)
    )
    op.add_column(
        "opening_details",
        sa.Column(
            "modalities", sqlite.JSON(), server_default=sa.text("'[]'"), nullable=True
        ),
    )
    op.add_column("intake_details", sa.Column("website", sa.TEXT(), nullable=True))
    op.add_column(
        "intake_details",
        sa.Column(
            "settings", sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "intake_details",
        sa.Column(
            "services", sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "intake_details",
        sa.Column(
            "age_groups", sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "intake_details",
        sa.Column(
            "languages",
            sqlite.JSON(),
            server_default=sa.text("'[\"en\"]'"),
            nullable=False,
        ),
    )
    op.add_column(
        "intake_details",
        sa.Column(
            "genders", sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "intake_details", sa.Column("referral_instructions", sa.TEXT(), nullable=True)
    )
    op.add_column(
        "intake_details",
        sa.Column(
            "modalities", sqlite.JSON(), server_default=sa.text("'[]'"), nullable=True
        ),
    )
    # ### end Alembic commands ###
