"""drop organizations.is_demo

Revision ID: 7092114bc0c0
Revises: f3c128112fa7
Create Date: 2026-06-10 22:17:39.103797

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7092114bc0c0"
down_revision: Union[str, None] = "f3c128112fa7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "is_demo")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations",
        sa.Column(
            "is_demo", sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False
        ),
    )
    # ### end Alembic commands ###
