"""drop treatment_modality from referral_details

Revision ID: 89e2e863e214
Revises: 57161384b6db
Create Date: 2026-06-13 18:40:47.656152

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89e2e863e214"
down_revision: Union[str, None] = "57161384b6db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("referral_details", "treatment_modality")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "referral_details", sa.Column("treatment_modality", sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
