"""add acceptable_license_types to referral_details

License-class disjunction on the referred provider (#1358 PR-b). Adds a
JSON-list column to ``referral_details``:

- ``referral_details.acceptable_license_types`` — set of acceptable
  ``LicenseType`` tokens. Empty array = "no constraint" (any license
  class accepted). Captures the "psychiatrist OR PMHNP" disjunction
  surfaced in the corpus analysis (#1355) that the existing
  ``services`` column can't express — a PCP, PA, or non-psychiatric NP
  could technically deliver ``medication_management``.

The column is NOT NULL with a server-side default of ``'[]'``; the
SQLite/Postgres JSON column stores an empty array for every existing
row at upgrade time, so there is no separate backfill step. No CHECK
constraint on JSON array members — the vocabulary (``LICENSE_TYPES``)
is enforced on the wire by Pydantic, mirroring the pattern used by
``services`` / ``age_groups`` / ``affirming_identities``.

Downgrade drops the column; data loss is the expected outcome of
reverting an additive vocabulary column.

Revision ID: da5c996ccd85
Revises: 2621a96f2e46
Create Date: 2026-06-10 19:15:43.028707

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da5c996ccd85"
down_revision: Union[str, None] = "2621a96f2e46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "referral_details",
        sa.Column(
            "acceptable_license_types",
            sa.JSON(),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("referral_details", "acceptable_license_types")
    # ### end Alembic commands ###
