"""add steady-state profile cols to clinicians, affiliations, programs (PR-f sub-1)

First of three migrations for the #1358 PR-f normalization:
``OpeningDetail`` ↔ ``ClinicianAffiliation`` and ``IntakeDetail`` ↔
``Program``. Pure schema add — *no reads or writes are flipped yet*.

What this migration adds:

- ``clinician_affiliations`` gains ``services``, ``settings``,
  ``modalities``, ``age_groups``, ``genders``, ``website``,
  ``referral_instructions`` (each NOT NULL with the default the same
  field had on ``OpeningDetail``), plus
  ``currently_accepting_new_patients: bool`` (denormalized lifecycle
  cache, default ``False``).
- ``clinicians`` gains ``languages`` (NOT NULL, default ``["en"]``) —
  per #1358 the only field from the old ``OpeningDetail`` set that
  belongs on the *person*, not on the per-affiliation row.
- ``programs`` gains the symmetric set: ``services``, ``settings``,
  ``modalities``, ``age_groups``, ``genders``, ``languages``,
  ``website``, ``referral_instructions``, plus
  ``currently_accepting_new_patients``. Same field-by-field rationale,
  for the ``IntakeDetail`` → ``Program`` half of the refactor.

What this migration does *not* do:

- It does not backfill from existing ``opening_details`` /
  ``intake_details`` rows. The sibling data migration
  ``<NEXT_REV>`` (the one immediately following this in the chain)
  copies values across, per the "schema-only is the norm; data
  backfills go in separate migrations" convention in
  ``alembic/README.md``. The split mirrors ``82b7dce71362`` (schema)
  paired with ``9501786659b3`` (data).
- It does not remove any columns from ``opening_details`` /
  ``intake_details``. Those rows are still the source of truth for
  reads in this PR; sub-PR 2 flips reads, sub-PR 3 removes them.

Downgrade drops the new columns. Any data the backfill copied into
them is lost — that's intentional for a pure additive forward step.

Revision ID: e3e0a73e9bc5
Revises: ee1a1aca3db2
Create Date: 2026-06-10 20:43:13.634480

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3e0a73e9bc5"
down_revision: Union[str, None] = "ee1a1aca3db2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clinician_affiliations",
        sa.Column(
            "services", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "clinician_affiliations",
        sa.Column(
            "settings", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "clinician_affiliations",
        sa.Column(
            "modalities", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "clinician_affiliations",
        sa.Column(
            "age_groups", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "clinician_affiliations",
        sa.Column("genders", sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    )
    op.add_column(
        "clinician_affiliations", sa.Column("website", sa.Text(), nullable=True)
    )
    op.add_column(
        "clinician_affiliations",
        sa.Column("referral_instructions", sa.Text(), nullable=True),
    )
    op.add_column(
        "clinician_affiliations",
        sa.Column(
            "currently_accepting_new_patients",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.add_column(
        "clinicians",
        sa.Column(
            "languages", sa.JSON(), server_default=sa.text("'[\"en\"]'"), nullable=False
        ),
    )
    op.add_column(
        "programs",
        sa.Column(
            "services", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "programs",
        sa.Column(
            "settings", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "programs",
        sa.Column(
            "modalities", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "programs",
        sa.Column(
            "age_groups", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "programs",
        sa.Column("genders", sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    )
    op.add_column(
        "programs",
        sa.Column(
            "languages", sa.JSON(), server_default=sa.text("'[\"en\"]'"), nullable=False
        ),
    )
    op.add_column("programs", sa.Column("website", sa.Text(), nullable=True))
    op.add_column(
        "programs", sa.Column("referral_instructions", sa.Text(), nullable=True)
    )
    op.add_column(
        "programs",
        sa.Column(
            "currently_accepting_new_patients",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("programs", "currently_accepting_new_patients")
    op.drop_column("programs", "referral_instructions")
    op.drop_column("programs", "website")
    op.drop_column("programs", "languages")
    op.drop_column("programs", "genders")
    op.drop_column("programs", "age_groups")
    op.drop_column("programs", "modalities")
    op.drop_column("programs", "settings")
    op.drop_column("programs", "services")
    op.drop_column("clinicians", "languages")
    op.drop_column("clinician_affiliations", "currently_accepting_new_patients")
    op.drop_column("clinician_affiliations", "referral_instructions")
    op.drop_column("clinician_affiliations", "website")
    op.drop_column("clinician_affiliations", "genders")
    op.drop_column("clinician_affiliations", "age_groups")
    op.drop_column("clinician_affiliations", "modalities")
    op.drop_column("clinician_affiliations", "settings")
    op.drop_column("clinician_affiliations", "services")
    # ### end Alembic commands ###
