"""add clinical_niches to clinicians and referral_details

Clinical-niche tagging (#1358 PR-c). Adds a JSON-list column to two
tables, symmetric to the affirming-identity pair:

- ``clinicians.clinical_niches`` — person-level claim (niches the
  clinician covers, e.g. "DGBI", "ADHD in women", "complex trauma"). The
  niche moves with the clinician across affiliations, like credentials.
- ``referral_details.clinical_niches`` — referrer-side request constraint
  (matches the provider claim above).

Both columns are NOT NULL with a server-side default of ``'[]'``; the
JSON column stores an empty array for every existing row at upgrade
time, so there is no separate backfill step. Deliberately **free-form
text** — no SQL CHECK and no Pydantic ``Literal`` against a closed
vocabulary. The referral corpus shows the niche vocabulary is too
open-ended to commit to an enum on day one ("DGBI", "catatonia",
"psychedelic-knowledgeable", "minor consent"); per the issue's PR-c
plan, heavily-used tags will be promoted to a `Literal[*ENUM]` once
usage patterns stabilize. Each tag is a stripped non-empty string,
enforced on the wire by the schema validator.

Downgrade drops both columns; data loss is the expected outcome of
reverting an additive vocabulary column.

Revision ID: ee1a1aca3db2
Revises: da5c996ccd85
Create Date: 2026-06-10 19:31:26.952599

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee1a1aca3db2"
down_revision: Union[str, None] = "da5c996ccd85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clinicians",
        sa.Column(
            "clinical_niches", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "referral_details",
        sa.Column(
            "clinical_niches", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("referral_details", "clinical_niches")
    op.drop_column("clinicians", "clinical_niches")
    # ### end Alembic commands ###
