"""intake gains profile fields; program slims to steady-state context

Mirrors `39bfbf922221` (the clinician-opening side) on the program-intake
side: the intake post becomes self-describing while the Program becomes
thin steady-state context.

``intake_details`` gains ``services`` / ``services_other_text`` /
``age_groups`` / ``genders`` / ``cost`` (the announcement profile;
``services`` on the ``ReferralService`` vocabulary). No ``session_format``
— a Program is a single group offering with no in-person/virtual axis.

``programs`` drops the columns that moved onto the intake post
(``services`` / ``settings`` / ``modalities`` / ``age_groups`` /
``genders``). Steady-state context — name, state_preference, languages,
website / referral_instructions, the accepting flags — stays. The Program
JSON columns carry no CHECK, so plain ``drop_column`` suffices. No
backfill: the dropped values are discarded.

Revision ID: ffaa7b220297
Revises: 39bfbf922221
Create Date: 2026-06-21 10:23:58.350092

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffaa7b220297"
down_revision: Union[str, None] = "39bfbf922221"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "intake_details",
        sa.Column(
            "services", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "intake_details", sa.Column("services_other_text", sa.Text(), nullable=True)
    )
    op.add_column(
        "intake_details",
        sa.Column(
            "age_groups", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "intake_details",
        sa.Column("genders", sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    )
    op.add_column("intake_details", sa.Column("cost", sa.Text(), nullable=True))
    op.drop_column("programs", "age_groups")
    op.drop_column("programs", "services")
    op.drop_column("programs", "genders")
    op.drop_column("programs", "modalities")
    op.drop_column("programs", "settings")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "programs",
        sa.Column(
            "settings", sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "programs",
        sa.Column(
            "modalities", sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "programs",
        sa.Column(
            "genders", sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "programs",
        sa.Column(
            "services", sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.add_column(
        "programs",
        sa.Column(
            "age_groups", sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
    )
    op.drop_column("intake_details", "cost")
    op.drop_column("intake_details", "genders")
    op.drop_column("intake_details", "age_groups")
    op.drop_column("intake_details", "services_other_text")
    op.drop_column("intake_details", "services")
    # ### end Alembic commands ###
