"""Tests for `ProviderRepository`.

Exercises CRUD on the parent `Provider` row plus per-sub-table
CRUD (licensures, educations, certifications). The cascade-delete test
verifies that deleting a provider removes its credential rows via the
combined ORM cascade and FK `ON DELETE CASCADE` (the test engine sets
`PRAGMA foreign_keys = ON`). The list-with-filter tests cover the JOIN
through `provider_licensures` and `.distinct()` de-dup behavior.
"""

import uuid

import pytest
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from src.domain.logic.providers.repository import ProviderRepository
from src.domain.models import (
    Provider,
    ProviderCertification,
    ProviderEducation,
    ProviderLicensure,
    User,
)
from tests.helpers import (
    create_test_user,
    make_provider,
    make_provider_certification,
    make_provider_education,
    make_provider_licensure,
)

pytestmark = pytest.mark.asyncio


async def _seed_user(
    db_test_session_manager: async_sessionmaker[AsyncSession],
) -> User:
    """Persist a fresh user and return the (unbound) ORM instance.

    The returned object has the id generated by `create_test_user`; the
    caller can use it as a value (e.g. `user.id`) without re-attaching."""
    user = create_test_user(username=f"owner-{uuid.uuid4()}")
    async with db_test_session_manager() as session:
        async with session.begin():
            session.add(user)
    return user


# --- Provider CRUD --------------------------------------------------------


async def test_create_provider_persists_row(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        created = await repo.create(
            Provider(
                owner_id=user.id,
                practice_name="Acme Health",
                location_city="Springfield",
                location_state="IL",
                location_zip="62701",
                in_person_sessions="yes",
                virtual_sessions="no",
            )
        )
        await session.commit()
        provider_id = created.id

    async with db_test_session_manager() as session:
        row = (
            (await session.execute(select(Provider).filter(Provider.id == provider_id)))
            .scalars()
            .first()
        )
        assert row is not None
        assert row.owner_id == user.id
        assert row.practice_name == "Acme Health"


async def test_get_by_id_finds_created_provider(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        created = await repo.create(
            Provider(
                owner_id=user.id,
                practice_name="Acme",
                location_city="Springfield",
                location_state="IL",
                location_zip="62701",
                in_person_sessions="yes",
                virtual_sessions="no",
            )
        )
        await session.commit()
        provider_id = created.id

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        found = await repo.get_by_model_id(Provider, provider_id)
        assert found is not None
        assert found.id == provider_id


async def test_get_by_user_id_finds_created_provider(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        await repo.create(
            Provider(
                owner_id=user.id,
                practice_name="Acme",
                location_city="Springfield",
                location_state="IL",
                location_zip="62701",
                in_person_sessions="yes",
                virtual_sessions="no",
            )
        )
        await session.commit()

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        found = await repo.get_by_user_id(user.id)
        assert found is not None
        assert found.owner_id == user.id


async def test_update_provider_changes_fields_visible_on_refetch(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        created = await repo.create(
            Provider(
                owner_id=user.id,
                practice_name="Original",
                location_city="Springfield",
                location_state="IL",
                location_zip="62701",
                in_person_sessions="yes",
                virtual_sessions="no",
            )
        )
        await session.commit()
        provider_id = created.id

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        provider = await repo.get_by_model_id(Provider, provider_id)
        assert provider is not None
        await repo.patch(provider, practice_name="Renamed", location_city="Chicago")
        await session.commit()

    async with db_test_session_manager() as session:
        row = (
            (await session.execute(select(Provider).filter(Provider.id == provider_id)))
            .scalars()
            .first()
        )
        assert row.practice_name == "Renamed"
        assert row.location_city == "Chicago"


async def test_insurance_fields_round_trip(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    """The five #449 insurance/payment columns persist + read back."""
    user = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        created = await repo.create(
            Provider(
                owner_id=user.id,
                practice_name="Insurance Test",
                location_city="Springfield",
                location_state="IL",
                location_zip="62701",
                in_person_sessions="yes",
                virtual_sessions="no",
                accepts_out_of_network=True,
                in_network_carriers=["aetna", "cigna"],
                sliding_scale=True,
                cost="$200 - $400 per session",
            )
        )
        await session.commit()
        provider_id = created.id

    async with db_test_session_manager() as session:
        row = (
            (await session.execute(select(Provider).filter(Provider.id == provider_id)))
            .scalars()
            .first()
        )
        assert row.accepts_out_of_network is True
        assert row.in_network_carriers == ["aetna", "cigna"]
        assert row.sliding_scale is True
        assert row.cost == "$200 - $400 per session"


async def test_insurance_fields_default_to_oon_only(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    """Omitting the new columns falls back to the server defaults:
    empty carrier list (no in-network) + `accepts_out_of_network=True`
    (most practices accept OON), no sliding scale."""
    user = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        created = await repo.create(
            Provider(
                owner_id=user.id,
                practice_name="Defaults Test",
                location_city="Springfield",
                location_state="IL",
                location_zip="62701",
                in_person_sessions="yes",
                virtual_sessions="no",
            )
        )
        await session.commit()
        provider_id = created.id

    async with db_test_session_manager() as session:
        row = (
            (await session.execute(select(Provider).filter(Provider.id == provider_id)))
            .scalars()
            .first()
        )
        assert row.accepts_out_of_network is True
        assert row.in_network_carriers == []
        assert row.sliding_scale is False
        assert row.cost is None


async def test_delete_provider_cascades_licensures(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    """Deleting a provider must remove its sub-rows via cascade. Covers
    licensures explicitly and education/certification incidentally."""
    user = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        async with session.begin():
            provider = make_provider(owner_id=user.id)
            session.add(provider)
            await session.flush()
            session.add(
                make_provider_licensure(
                    provider_id=provider.id, license_type="lcsw", issuing_state="IL"
                )
            )
            session.add(
                make_provider_licensure(
                    provider_id=provider.id, license_type="lpc", issuing_state="CA"
                )
            )
            session.add(make_provider_education(provider_id=provider.id))
            session.add(make_provider_certification(provider_id=provider.id))
            provider_id = provider.id

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        provider = await repo.get_by_model_id(Provider, provider_id)
        assert provider is not None
        await repo.delete(provider)
        await session.commit()

    async with db_test_session_manager() as session:
        provider_row = (
            (await session.execute(select(Provider).filter(Provider.id == provider_id)))
            .scalars()
            .first()
        )
        licensure_rows = (
            (
                await session.execute(
                    select(ProviderLicensure).filter(
                        ProviderLicensure.provider_id == provider_id
                    )
                )
            )
            .scalars()
            .all()
        )
        education_rows = (
            (
                await session.execute(
                    select(ProviderEducation).filter(
                        ProviderEducation.provider_id == provider_id
                    )
                )
            )
            .scalars()
            .all()
        )
        certification_rows = (
            (
                await session.execute(
                    select(ProviderCertification).filter(
                        ProviderCertification.provider_id == provider_id
                    )
                )
            )
            .scalars()
            .all()
        )
        assert provider_row is None
        assert licensure_rows == []
        assert education_rows == []
        assert certification_rows == []


# --- list_providers ------------------------------------------------------


async def test_list_providers_no_filters_returns_all(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user_a = await _seed_user(db_test_session_manager)
    user_b = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        async with session.begin():
            session.add(make_provider(owner_id=user_a.id))
            session.add(make_provider(owner_id=user_b.id))

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        providers = await repo.list_providers()
        assert len(providers) == 2


async def test_list_providers_filtered_by_license_type(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user_a = await _seed_user(db_test_session_manager)
    user_b = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        async with session.begin():
            provider_a = make_provider(owner_id=user_a.id)
            provider_b = make_provider(owner_id=user_b.id)
            session.add_all([provider_a, provider_b])
            await session.flush()
            session.add(
                make_provider_licensure(
                    provider_id=provider_a.id, license_type="lcsw", issuing_state="IL"
                )
            )
            session.add(
                make_provider_licensure(
                    provider_id=provider_b.id, license_type="lpc", issuing_state="IL"
                )
            )
            keep_id = provider_a.id

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        providers = await repo.list_providers(license_type=["lcsw"])
        assert [p.id for p in providers] == [keep_id]


async def test_list_providers_filtered_by_issuing_state(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user_a = await _seed_user(db_test_session_manager)
    user_b = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        async with session.begin():
            provider_a = make_provider(owner_id=user_a.id)
            provider_b = make_provider(owner_id=user_b.id)
            session.add_all([provider_a, provider_b])
            await session.flush()
            session.add(
                make_provider_licensure(
                    provider_id=provider_a.id, license_type="lcsw", issuing_state="CA"
                )
            )
            session.add(
                make_provider_licensure(
                    provider_id=provider_b.id, license_type="lcsw", issuing_state="IL"
                )
            )
            keep_id = provider_a.id

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        providers = await repo.list_providers(issuing_state=["CA"])
        assert [p.id for p in providers] == [keep_id]


async def test_list_providers_combined_filter_is_anded(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    """Both filters must match on the same licensure row to select a provider."""
    user_a = await _seed_user(db_test_session_manager)
    user_b = await _seed_user(db_test_session_manager)
    user_c = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        async with session.begin():
            provider_a = make_provider(owner_id=user_a.id)
            provider_b = make_provider(owner_id=user_b.id)
            provider_c = make_provider(owner_id=user_c.id)
            session.add_all([provider_a, provider_b, provider_c])
            await session.flush()
            # A: matches both filters
            session.add(
                make_provider_licensure(
                    provider_id=provider_a.id, license_type="lcsw", issuing_state="CA"
                )
            )
            # B: matches license_type only
            session.add(
                make_provider_licensure(
                    provider_id=provider_b.id, license_type="lcsw", issuing_state="IL"
                )
            )
            # C: matches issuing_state only
            session.add(
                make_provider_licensure(
                    provider_id=provider_c.id, license_type="lpc", issuing_state="CA"
                )
            )
            keep_id = provider_a.id

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        providers = await repo.list_providers(
            license_type=["lcsw"], issuing_state=["CA"]
        )
        assert [p.id for p in providers] == [keep_id]


async def test_list_providers_distinct_when_multiple_licensures_match(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    """A provider with two matching licensures must appear exactly once."""
    user = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        async with session.begin():
            provider = make_provider(owner_id=user.id)
            session.add(provider)
            await session.flush()
            session.add(
                make_provider_licensure(
                    provider_id=provider.id,
                    license_type="lcsw",
                    issuing_state="IL",
                    license_number="L-1",
                )
            )
            session.add(
                make_provider_licensure(
                    provider_id=provider.id,
                    license_type="lcsw",
                    issuing_state="CA",
                    license_number="L-2",
                )
            )

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        providers = await repo.list_providers(license_type=["lcsw"])
        assert len(providers) == 1


# --- Sub-table CRUD round-trips -----------------------------------------


async def test_licensure_crud_round_trip(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        async with session.begin():
            provider = make_provider(owner_id=user.id)
            session.add(provider)
            await session.flush()
            provider_id = provider.id

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        provider = await repo.get_by_model_id(Provider, provider_id)
        licensure = await repo.add_child(
            provider,
            "licensures",
            ProviderLicensure(
                license_type="lcsw",
                license_number="L-1",
                issuing_state="IL",
            ),
        )
        await session.commit()
        licensure_id = licensure.id

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        found = await repo.get_by_model_id(ProviderLicensure, licensure_id)
        assert found is not None
        await repo.patch(found, license_number="L-2")
        await session.commit()

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        found = await repo.get_by_model_id(ProviderLicensure, licensure_id)
        assert found.license_number == "L-2"
        await repo.delete(found)
        await session.commit()

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        assert await repo.get_by_model_id(ProviderLicensure, licensure_id) is None


async def test_education_crud_round_trip(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        async with session.begin():
            provider = make_provider(owner_id=user.id)
            session.add(provider)
            await session.flush()
            provider_id = provider.id

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        provider = await repo.get_by_model_id(Provider, provider_id)
        education = await repo.add_child(
            provider,
            "educations",
            ProviderEducation(
                education_type="msw",
                institution="State U",
            ),
        )
        await session.commit()
        education_id = education.id

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        found = await repo.get_by_model_id(ProviderEducation, education_id)
        assert found is not None
        await repo.patch(found, institution="State U Renamed")
        await session.commit()

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        found = await repo.get_by_model_id(ProviderEducation, education_id)
        assert found.institution == "State U Renamed"
        await repo.delete(found)
        await session.commit()

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        assert await repo.get_by_model_id(ProviderEducation, education_id) is None


async def test_certification_crud_round_trip(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        async with session.begin():
            provider = make_provider(owner_id=user.id)
            session.add(provider)
            await session.flush()
            provider_id = provider.id

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        provider = await repo.get_by_model_id(Provider, provider_id)
        cert = await repo.add_child(
            provider,
            "certifications",
            ProviderCertification(
                certification_type="emdr",
                certifying_body="EMDRIA",
            ),
        )
        await session.commit()
        cert_id = cert.id

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        found = await repo.get_by_model_id(ProviderCertification, cert_id)
        assert found is not None
        await repo.patch(found, certifying_body="Updated Body")
        await session.commit()

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        found = await repo.get_by_model_id(ProviderCertification, cert_id)
        assert found.certifying_body == "Updated Body"
        await repo.delete(found)
        await session.commit()

    async with db_test_session_manager() as session:
        repo = ProviderRepository(session)
        assert await repo.get_by_model_id(ProviderCertification, cert_id) is None
