"""Tests for `ClinicianRepository`.

Exercises CRUD on the parent `Clinician` row plus per-sub-table
CRUD (licensures, educations, certifications). The cascade-delete test
verifies that deleting a clinician removes its credential rows via the
combined ORM cascade and FK `ON DELETE CASCADE` (the test engine sets
`PRAGMA foreign_keys = ON`). The list-with-filter tests cover the JOIN
through `provider_licensures` (credit model name) and `.distinct()` de-dup behavior.

The Clinician's practice display name lives on
``clinician.org.name``; fixtures here use
:func:`make_clinician_with_org` to wire each Clinician to a root
Organization at construction time.
"""

import uuid

import pytest
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from src.domain.logic.clinicians.repository import ClinicianRepository
from src.domain.models import (
    Clinician,
    ClinicianCertification,
    ClinicianEducation,
    ClinicianLicensure,
    User,
)
from tests.helpers import (
    create_test_user,
    make_clinician_certification,
    make_clinician_education,
    make_clinician_licensure,
    make_clinician_with_org,
)

pytestmark = pytest.mark.asyncio


async def _seed_user(
    db_test_session_manager: async_sessionmaker[AsyncSession],
) -> User:
    """Persist a fresh user and return the (unbound) ORM instance.

    The returned object has the id generated by `create_test_user`; the
    caller can use it as a value (e.g. `user.id`) without re-attaching."""
    user = create_test_user(username=f"owner-{uuid.uuid4()}")
    async with db_test_session_manager() as session:
        async with session.begin():
            session.add(user)
    return user


async def _seed_clinician(
    db_test_session_manager: async_sessionmaker[AsyncSession],
    *,
    owner_id: uuid.UUID,
    practice_name: str = "Acme Health",
    **overrides,
) -> Clinician:
    """Persist a Clinician + its Organization via ``make_clinician_with_org``
    and return the (unbound) ORM instance. Save-update cascade picks the
    Org up when the Clinician is added."""
    async with db_test_session_manager() as session:
        async with session.begin():
            clinician = make_clinician_with_org(
                owner_id=owner_id, practice_name=practice_name, **overrides
            )
            session.add(clinician)
    return clinician


# --- Clinician CRUD --------------------------------------------------------


async def test_create_clinician_persists_row(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user = await _seed_user(db_test_session_manager)
    created = await _seed_clinician(
        db_test_session_manager, owner_id=user.id, practice_name="Acme Health"
    )

    async with db_test_session_manager() as session:
        row = (
            (
                await session.execute(
                    select(Clinician).filter(Clinician.id == created.id)
                )
            )
            .scalars()
            .first()
        )
        assert row is not None
        assert row.owner_id == user.id
        assert row.org.name == "Acme Health"


async def test_get_by_id_finds_created_clinician(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user = await _seed_user(db_test_session_manager)
    created = await _seed_clinician(
        db_test_session_manager, owner_id=user.id, practice_name="Acme"
    )

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        found = await repo.get_by_model_id(Clinician, created.id)
        assert found is not None
        assert found.id == created.id


async def test_get_by_user_id_finds_created_clinician(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user = await _seed_user(db_test_session_manager)
    await _seed_clinician(db_test_session_manager, owner_id=user.id)

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        found = await repo.get_by_user_id(user.id)
        assert found is not None
        assert found.owner_id == user.id


async def test_update_clinician_changes_fields_visible_on_refetch(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user = await _seed_user(db_test_session_manager)
    created = await _seed_clinician(
        db_test_session_manager, owner_id=user.id, practice_name="Original"
    )

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        clinician = await repo.get_by_model_id(Clinician, created.id)
        assert clinician is not None
        await repo.patch(clinician, location_city="Chicago")
        await session.commit()

    async with db_test_session_manager() as session:
        row = (
            (
                await session.execute(
                    select(Clinician).filter(Clinician.id == created.id)
                )
            )
            .scalars()
            .first()
        )
        assert row.location_city == "Chicago"


async def test_npi_round_trips(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    """A 10-digit `npi` persists and reads back unchanged."""
    user = await _seed_user(db_test_session_manager)
    created = await _seed_clinician(
        db_test_session_manager,
        owner_id=user.id,
        practice_name="NPI Test",
        npi="1234567890",
    )

    async with db_test_session_manager() as session:
        row = (
            (
                await session.execute(
                    select(Clinician).filter(Clinician.id == created.id)
                )
            )
            .scalars()
            .first()
        )
        assert row.npi == "1234567890"


async def test_npi_defaults_to_null(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user = await _seed_user(db_test_session_manager)
    created = await _seed_clinician(
        db_test_session_manager, owner_id=user.id, practice_name="No NPI"
    )

    async with db_test_session_manager() as session:
        row = (
            (
                await session.execute(
                    select(Clinician).filter(Clinician.id == created.id)
                )
            )
            .scalars()
            .first()
        )
        assert row.npi is None


async def test_insurance_fields_round_trip(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    """The five #449 insurance/payment columns persist + read back."""
    user = await _seed_user(db_test_session_manager)
    created = await _seed_clinician(
        db_test_session_manager,
        owner_id=user.id,
        practice_name="Insurance Test",
        accepts_out_of_network=True,
        in_network_carriers=["aetna", "cigna"],
        sliding_scale=True,
        cost="$200 - $400 per session",
    )

    async with db_test_session_manager() as session:
        row = (
            (
                await session.execute(
                    select(Clinician).filter(Clinician.id == created.id)
                )
            )
            .scalars()
            .first()
        )
        assert row.accepts_out_of_network is True
        assert row.in_network_carriers == ["aetna", "cigna"]
        assert row.sliding_scale is True
        assert row.cost == "$200 - $400 per session"


async def test_insurance_fields_default_to_oon_only(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    """Omitting the new columns falls back to the server defaults:
    empty carrier list (no in-network) + `accepts_out_of_network=True`
    (most practices accept OON), no sliding scale."""
    user = await _seed_user(db_test_session_manager)
    created = await _seed_clinician(db_test_session_manager, owner_id=user.id)

    async with db_test_session_manager() as session:
        row = (
            (
                await session.execute(
                    select(Clinician).filter(Clinician.id == created.id)
                )
            )
            .scalars()
            .first()
        )
        assert row.accepts_out_of_network is True
        assert row.in_network_carriers == []
        assert row.sliding_scale is False
        assert row.cost is None


async def test_delete_clinician_cascades_to_credentials(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    """Deleting a Clinician cascades to its credential sub-rows via the
    ORM `cascade="all, delete-orphan"` on the clinician relationships.
    Mirrors the model-level test in `test_provider_models.py` (model class names intentionally kept).
    """
    user = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        async with session.begin():
            clinician = make_clinician_with_org(owner_id=user.id)
            session.add(clinician)
            await session.flush()
            session.add(
                make_clinician_licensure(
                    clinician_id=clinician.id,
                    license_type="lcsw",
                    issuing_state="IL",
                )
            )
            session.add(
                make_clinician_licensure(
                    clinician_id=clinician.id,
                    license_type="lpc",
                    issuing_state="CA",
                )
            )
            session.add(make_clinician_education(clinician_id=clinician.id))
            session.add(make_clinician_certification(clinician_id=clinician.id))
            clinician_id = clinician.id

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        clinician = await repo.get_by_model_id(Clinician, clinician_id)
        assert clinician is not None
        await repo.delete(clinician)
        await session.commit()

    async with db_test_session_manager() as session:
        clinician_row = (
            (
                await session.execute(
                    select(Clinician).filter(Clinician.id == clinician_id)
                )
            )
            .scalars()
            .first()
        )
        licensure_rows = (
            (
                await session.execute(
                    select(ClinicianLicensure).filter(
                        ClinicianLicensure.clinician_id == clinician_id
                    )
                )
            )
            .scalars()
            .all()
        )
        education_rows = (
            (
                await session.execute(
                    select(ClinicianEducation).filter(
                        ClinicianEducation.clinician_id == clinician_id
                    )
                )
            )
            .scalars()
            .all()
        )
        certification_rows = (
            (
                await session.execute(
                    select(ClinicianCertification).filter(
                        ClinicianCertification.clinician_id == clinician_id
                    )
                )
            )
            .scalars()
            .all()
        )
        assert clinician_row is None
        assert len(licensure_rows) == 0
        assert len(education_rows) == 0
        assert len(certification_rows) == 0


# --- list_clinicians -----------------------------------------------------------------------------------------------------


async def test_list_clinicians_no_filters_returns_all(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user_a = await _seed_user(db_test_session_manager)
    user_b = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        async with session.begin():
            session.add(make_clinician_with_org(owner_id=user_a.id))
            session.add(
                make_clinician_with_org(owner_id=user_b.id, practice_name="Other")
            )

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        clinicians = await repo.list_clinicians()
        assert len(clinicians) == 2


async def test_list_clinicians_filtered_by_license_type(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user_a = await _seed_user(db_test_session_manager)
    user_b = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        async with session.begin():
            clinician_a = make_clinician_with_org(owner_id=user_a.id)
            clinician_b = make_clinician_with_org(
                owner_id=user_b.id, practice_name="Other"
            )
            session.add_all([clinician_a, clinician_b])
            await session.flush()
            session.add(
                make_clinician_licensure(
                    clinician_id=clinician_a.id,
                    license_type="lcsw",
                    issuing_state="IL",
                )
            )
            session.add(
                make_clinician_licensure(
                    clinician_id=clinician_b.id,
                    license_type="lpc",
                    issuing_state="IL",
                )
            )
            keep_id = clinician_a.id

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        clinicians = await repo.list_clinicians(license_type=["lcsw"])
        assert [p.id for p in clinicians] == [keep_id]


async def test_list_clinicians_filtered_by_issuing_state(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user_a = await _seed_user(db_test_session_manager)
    user_b = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        async with session.begin():
            clinician_a = make_clinician_with_org(owner_id=user_a.id)
            clinician_b = make_clinician_with_org(
                owner_id=user_b.id, practice_name="Other"
            )
            session.add_all([clinician_a, clinician_b])
            await session.flush()
            session.add(
                make_clinician_licensure(
                    clinician_id=clinician_a.id,
                    license_type="lcsw",
                    issuing_state="CA",
                )
            )
            session.add(
                make_clinician_licensure(
                    clinician_id=clinician_b.id,
                    license_type="lcsw",
                    issuing_state="IL",
                )
            )
            keep_id = clinician_a.id

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        clinicians = await repo.list_clinicians(issuing_state=["CA"])
        assert [p.id for p in clinicians] == [keep_id]


async def test_list_clinicians_combined_filter_is_anded(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    """Both filters must match on the same licensure row to select a clinician."""
    user_a = await _seed_user(db_test_session_manager)
    user_b = await _seed_user(db_test_session_manager)
    user_c = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        async with session.begin():
            clinician_a = make_clinician_with_org(owner_id=user_a.id)
            clinician_b = make_clinician_with_org(
                owner_id=user_b.id, practice_name="Two"
            )
            clinician_c = make_clinician_with_org(
                owner_id=user_c.id, practice_name="Three"
            )
            session.add_all([clinician_a, clinician_b, clinician_c])
            await session.flush()
            # A: matches both filters
            session.add(
                make_clinician_licensure(
                    clinician_id=clinician_a.id,
                    license_type="lcsw",
                    issuing_state="CA",
                )
            )
            # B: matches license_type only
            session.add(
                make_clinician_licensure(
                    clinician_id=clinician_b.id,
                    license_type="lcsw",
                    issuing_state="IL",
                )
            )
            # C: matches issuing_state only
            session.add(
                make_clinician_licensure(
                    clinician_id=clinician_c.id,
                    license_type="lpc",
                    issuing_state="CA",
                )
            )
            keep_id = clinician_a.id

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        clinicians = await repo.list_clinicians(
            license_type=["lcsw"], issuing_state=["CA"]
        )
        assert [p.id for p in clinicians] == [keep_id]


async def test_list_for_verification_returns_non_deleted_clinicians(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    """Eligibility for nightly verification is `deleted_at IS NULL` — see
    `ClinicianRepository.list_for_verification` docstring for the rationale.
    """
    import datetime

    user_a = await _seed_user(db_test_session_manager)
    user_b = await _seed_user(db_test_session_manager)
    user_c = await _seed_user(db_test_session_manager)

    kept_a = await _seed_clinician(db_test_session_manager, owner_id=user_a.id)
    kept_b = await _seed_clinician(
        db_test_session_manager, owner_id=user_b.id, practice_name="Other"
    )
    deleted = await _seed_clinician(
        db_test_session_manager, owner_id=user_c.id, practice_name="Gone"
    )

    async with db_test_session_manager() as session:
        async with session.begin():
            row = await session.get(Clinician, deleted.id)
            row.deleted_at = datetime.datetime.now(datetime.timezone.utc)

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        eligible = await repo.list_for_verification()
        assert {p.id for p in eligible} == {kept_a.id, kept_b.id}


async def test_list_clinicians_distinct_when_multiple_licensures_match(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    """A clinician with two matching licensures must appear exactly once."""
    user = await _seed_user(db_test_session_manager)

    async with db_test_session_manager() as session:
        async with session.begin():
            clinician_row = make_clinician_with_org(owner_id=user.id)
            session.add(clinician_row)
            await session.flush()
            session.add(
                make_clinician_licensure(
                    clinician_id=clinician_row.id,
                    license_type="lcsw",
                    issuing_state="IL",
                    license_number="L-1",
                )
            )
            session.add(
                make_clinician_licensure(
                    clinician_id=clinician_row.id,
                    license_type="lcsw",
                    issuing_state="CA",
                    license_number="L-2",
                )
            )

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        clinicians = await repo.list_clinicians(license_type=["lcsw"])
        assert len(clinicians) == 1


# --- Sub-table CRUD round-trips -----------------------------------------


async def test_licensure_crud_round_trip(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user = await _seed_user(db_test_session_manager)
    clinician = await _seed_clinician(db_test_session_manager, owner_id=user.id)

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        clinician = await repo.get_by_model_id(Clinician, clinician.id)
        licensure = await repo.add_child(
            clinician,
            "licensures",
            ClinicianLicensure(
                license_type="lcsw",
                license_number="L-1",
                issuing_state="IL",
            ),
        )
        await session.commit()
        licensure_id = licensure.id

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        found = await repo.get_by_model_id(ClinicianLicensure, licensure_id)
        assert found is not None
        await repo.patch(found, license_number="L-2")
        await session.commit()

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        found = await repo.get_by_model_id(ClinicianLicensure, licensure_id)
        assert found.license_number == "L-2"
        await repo.delete(found)
        await session.commit()

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        assert await repo.get_by_model_id(ClinicianLicensure, licensure_id) is None


async def test_education_crud_round_trip(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user = await _seed_user(db_test_session_manager)
    clinician = await _seed_clinician(db_test_session_manager, owner_id=user.id)

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        clinician = await repo.get_by_model_id(Clinician, clinician.id)
        education = await repo.add_child(
            clinician,
            "educations",
            ClinicianEducation(
                education_type="msw",
                institution="State U",
            ),
        )
        await session.commit()
        education_id = education.id

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        found = await repo.get_by_model_id(ClinicianEducation, education_id)
        assert found is not None
        await repo.patch(found, institution="State U Renamed")
        await session.commit()

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        found = await repo.get_by_model_id(ClinicianEducation, education_id)
        assert found.institution == "State U Renamed"
        await repo.delete(found)
        await session.commit()

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        assert await repo.get_by_model_id(ClinicianEducation, education_id) is None


async def test_certification_crud_round_trip(
    db_test_session_manager: async_sessionmaker[AsyncSession],
):
    user = await _seed_user(db_test_session_manager)
    clinician = await _seed_clinician(db_test_session_manager, owner_id=user.id)

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        clinician = await repo.get_by_model_id(Clinician, clinician.id)
        cert = await repo.add_child(
            clinician,
            "certifications",
            ClinicianCertification(
                certification_type="emdr",
                certifying_body="EMDRIA",
            ),
        )
        await session.commit()
        cert_id = cert.id

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        found = await repo.get_by_model_id(ClinicianCertification, cert_id)
        assert found is not None
        await repo.patch(found, certifying_body="Updated Body")
        await session.commit()

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        found = await repo.get_by_model_id(ClinicianCertification, cert_id)
        assert found.certifying_body == "Updated Body"
        await repo.delete(found)
        await session.commit()

    async with db_test_session_manager() as session:
        repo = ClinicianRepository(session)
        assert await repo.get_by_model_id(ClinicianCertification, cert_id) is None
