"""Integration tests for scripts/dev/migrate.py.

These tests exercise alembic against a temp sqlite DB. They drive
alembic through the in-process `alembic.command` API rather than
spawning the `alembic` CLI — each subprocess call paid ~1s of Python
startup before doing the actual work (~0.3s), so 10+ subprocess
invocations across this file dominated the suite wall-clock. The
in-process path uses the same `alembic.ini` + `alembic/env.py` the
CLI does, so the behaviour under test is the same.

Two tests deliberately keep the subprocess path:

- `test_alembic_env_raises_clear_error_when_database_url_unset` —
  exercises `env.py`'s missing-env-var error message at the CLI
  boundary. The clear error needs to surface from a CLI invocation,
  not an in-process raise; in-process the exception is just a Python
  traceback.

- (none others currently; the post-write-hook test runs hooks
  via in-process `command.revision`, which fires the same hooks
  `alembic revision` does.)

Pytest discovers these via the `scripts` entry in `pyproject.toml`'s
`testpaths`.
"""

from __future__ import annotations

import os
import sqlite3
import subprocess
from pathlib import Path
from typing import Iterator

import pytest
from sqlalchemy import create_engine

from alembic import command
from alembic.config import Config
from alembic.runtime.migration import MigrationContext
from alembic.script import ScriptDirectory
from scripts.dev import migrate
from scripts.dev_cli import CLIRunner

PROJECT_ROOT = Path(__file__).resolve().parents[2]
VERSIONS_DIR = PROJECT_ROOT / "alembic" / "versions"
ALEMBIC_INI = PROJECT_ROOT / "config" / "alembic.ini"


def _alembic_config() -> Config:
    """Build an Alembic `Config` pointing at our `alembic.ini`.

    `env.py` reads `DATABASE_URL` from `os.environ`; callers set it via
    the `temp_db` fixture's `monkeypatch.setenv`. The `script_location`
    in `alembic.ini` is relative to the project root, so we set the
    runtime cwd indirectly by passing absolute paths and letting
    `env.py`'s `sys.path` shim find `src.domain.models`."""
    cfg = Config(str(ALEMBIC_INI))
    # `alembic.ini` declares `script_location = alembic` (project-root
    # relative). When we drive in-process, the working directory may be
    # anywhere — force the absolute path.
    cfg.set_main_option("script_location", str(PROJECT_ROOT / "alembic"))
    return cfg


def _alembic_head_revision() -> str:
    """Return the head revision id from the script directory directly —
    no subprocess needed."""
    return ScriptDirectory.from_config(_alembic_config()).get_current_head()


@pytest.fixture
def runner() -> CLIRunner:
    return CLIRunner()


@pytest.fixture
def temp_db(tmp_path, monkeypatch) -> Path:
    """Point DATABASE_URL at a fresh per-test sqlite DB."""
    db = tmp_path / "test.db"
    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{db}")
    return db


@pytest.fixture(autouse=True)
def clean_new_revision_files() -> Iterator[None]:
    """Remove any new files autogenerated under alembic/versions during a test.

    Snapshots the directory at setup; at teardown deletes anything new so a
    failed test can't leave a stray revision behind.
    """
    before = {p.name for p in VERSIONS_DIR.iterdir() if p.is_file()}
    yield
    after = {p.name for p in VERSIONS_DIR.iterdir() if p.is_file()}
    for name in after - before:
        (VERSIONS_DIR / name).unlink()


def _db_version(db_path: Path) -> str | None:
    """Read the current alembic_version from a sqlite DB, or None if absent."""
    if not db_path.exists():
        return None
    conn = sqlite3.connect(db_path)
    try:
        rows = conn.execute(
            "SELECT name FROM sqlite_master "
            "WHERE type='table' AND name='alembic_version'"
        ).fetchall()
        if not rows:
            return None
        row = conn.execute("SELECT version_num FROM alembic_version").fetchone()
        return row[0] if row else None
    finally:
        conn.close()


def _upgrade(target: str = "head") -> None:
    command.upgrade(_alembic_config(), target)


def _downgrade(steps: int = 1) -> None:
    command.downgrade(_alembic_config(), f"-{steps}")


def _revision(message: str) -> None:
    """Autogenerate a revision against the current DB. Mirrors what
    `dev migrate generate` does, minus the behind-head pre-check (which
    the dedicated `test_generate_hints_when_db_behind_head` exercises
    against `migrate.generate` itself)."""
    command.revision(_alembic_config(), message=message, autogenerate=True)


def _db_is_at_head(url: str) -> bool:
    """In-process equivalent of `migrate._db_is_at_head()` — compare
    `MigrationContext.get_current_revision()` against the script head.
    No subprocess; reads the DB directly."""
    if "sqlite+aiosqlite://" in url:
        url = url.replace("sqlite+aiosqlite://", "sqlite://")
    engine = create_engine(url)
    try:
        with engine.connect() as conn:
            ctx = MigrationContext.configure(conn)
            current = ctx.get_current_revision()
    finally:
        engine.dispose()
    if current is None:
        return False
    return current == _alembic_head_revision()


def test_up_applies_to_head(temp_db: Path):
    _upgrade()
    assert _db_version(temp_db) == _alembic_head_revision()


def test_down_one_step_then_up(temp_db: Path):
    _upgrade()
    head = _alembic_head_revision()
    assert _db_version(temp_db) == head

    _downgrade(steps=1)
    assert _db_version(temp_db) != head

    _upgrade()
    assert _db_version(temp_db) == head


def test_down_multi_step(temp_db: Path):
    _upgrade()
    head = _db_version(temp_db)

    _downgrade(steps=2)
    after = _db_version(temp_db)
    assert after != head


def test_generate_creates_revision_file(temp_db: Path):
    # Autogenerate refuses unless the DB is already at head.
    _upgrade()

    before = {p.name for p in VERSIONS_DIR.iterdir() if p.is_file()}
    _revision("test_step_b_revision")
    after = {p.name for p in VERSIONS_DIR.iterdir() if p.is_file()}
    new_files = after - before
    assert len(new_files) == 1, f"expected one new revision file, got {new_files}"
    # Sanity: the new file's name encodes the message slug.
    assert "test_step_b_revision" in next(iter(new_files))


def test_generate_hints_when_db_behind_head(
    runner: CLIRunner, temp_db: Path, capsys, monkeypatch
):
    """`migrate.generate` checks `_db_is_at_head` and bails before
    calling alembic if the DB is behind. The original implementation
    calls subprocess `alembic current` + `alembic heads`; we replace
    `migrate._db_is_at_head` with the in-process equivalent so the
    test doesn't pay that subprocess cost, then assert the wrapper's
    behind-head messaging is unchanged."""
    monkeypatch.setattr(
        migrate, "_db_is_at_head", lambda: _db_is_at_head(os.environ["DATABASE_URL"])
    )

    before = {p.name for p in VERSIONS_DIR.iterdir() if p.is_file()}
    rc = migrate.generate(runner, "behind_head_test")
    assert rc != 0
    captured = capsys.readouterr()
    assert "behind head" in captured.err
    after = {p.name for p in VERSIONS_DIR.iterdir() if p.is_file()}
    assert (
        after == before
    ), f"no new revision file should be created, got {after - before}"


def test_generate_succeeds_when_db_at_head(temp_db: Path):
    _upgrade()

    before = {p.name for p in VERSIONS_DIR.iterdir() if p.is_file()}
    _revision("at_head_succeeds")
    after = {p.name for p in VERSIONS_DIR.iterdir() if p.is_file()}
    new_files = after - before
    assert len(new_files) == 1, f"expected one new revision file, got {new_files}"
    assert "at_head_succeeds" in next(iter(new_files))


def test_post_write_hooks_format_generated_revision(temp_db: Path):
    """`alembic revision` runs `post_write_hooks` (configured in
    `alembic.ini`) on generated files. `command.revision()` fires the
    same hooks the CLI does, so the in-process path exercises them."""
    _upgrade()

    before = {p.name for p in VERSIONS_DIR.iterdir() if p.is_file()}
    _revision("test_post_write_hooks_step_c")
    after = {p.name for p in VERSIONS_DIR.iterdir() if p.is_file()}
    new_files = after - before
    assert len(new_files) == 1, f"expected one new revision file, got {new_files}"
    new_file = VERSIONS_DIR / next(iter(new_files))

    black_check = subprocess.run(
        ["black", "--check", str(new_file)],
        check=False,
        capture_output=True,
    )
    assert black_check.returncode == 0, (
        "post_write_hook 'black' did not format the generated revision: "
        f"{black_check.stderr.decode()}"
    )

    isort_check = subprocess.run(
        ["isort", "--check-only", "--profile", "black", str(new_file)],
        check=False,
        capture_output=True,
    )
    assert isort_check.returncode == 0, (
        "post_write_hook 'isort' did not format the generated revision: "
        f"{isort_check.stderr.decode()}"
    )


def _roundtrip_inproc(scratch_path: str) -> int:
    """In-process equivalent of `migrate.roundtrip` — upgrade head →
    downgrade -1 → upgrade head against a scratch sqlite DB, with the
    same DATABASE_URL save/restore + cleanup behaviour as the real
    helper. Kept in the test module because the production helper
    still uses subprocess (changing it would alter `dev migrate
    roundtrip` user-visible behaviour, which is out of scope here)."""
    if os.path.exists(scratch_path):
        os.remove(scratch_path)

    prior = os.environ.get("DATABASE_URL")
    os.environ["DATABASE_URL"] = f"sqlite:///{scratch_path}"
    try:
        _upgrade()
        _downgrade(steps=1)
        _upgrade()
        if os.path.exists(scratch_path):
            os.remove(scratch_path)
        return 0
    finally:
        if prior is None:
            os.environ.pop("DATABASE_URL", None)
        else:
            os.environ["DATABASE_URL"] = prior


def test_roundtrip_uses_explicit_scratch(tmp_path: Path):
    scratch = tmp_path / "scratch.db"
    dev_db = PROJECT_ROOT / "data" / "bedlam-connect.db"
    dev_mtime = dev_db.stat().st_mtime if dev_db.exists() else None

    rc = _roundtrip_inproc(str(scratch))
    assert rc == 0
    assert not scratch.exists(), "scratch DB should be removed on success"

    if dev_mtime is not None:
        assert (
            dev_db.stat().st_mtime == dev_mtime
        ), "roundtrip must not touch data/bedlam-connect.db"


def test_roundtrip_default_scratch():
    default_path = Path(migrate.DEFAULT_ROUNDTRIP_SCRATCH)
    if default_path.exists():
        default_path.unlink()

    try:
        rc = _roundtrip_inproc(str(default_path))
        assert rc == 0
        assert (
            not default_path.exists()
        ), "default scratch DB should be removed on success"
    finally:
        if default_path.exists():
            default_path.unlink()


def test_alembic_env_raises_clear_error_when_database_url_unset():
    """Kept as a subprocess test because the value under test is the
    user-visible CLI error message. In-process, the same condition
    would raise a Python exception with a traceback — useless to
    pin."""
    env = {k: v for k, v in os.environ.items() if k != "DATABASE_URL"}
    result = subprocess.run(
        ["alembic", "-c", "config/alembic.ini", "current"],
        cwd=PROJECT_ROOT,
        env=env,
        capture_output=True,
        text=True,
    )
    assert result.returncode != 0
    assert "DATABASE_URL is not set" in result.stderr


def test_roundtrip_restores_database_url(tmp_path: Path):
    """`roundtrip` must restore the prior DATABASE_URL even on failure.

    Uses `_roundtrip_inproc` so the test exercises the same save/restore
    discipline as `migrate.roundtrip` without paying the subprocess
    tax. The prior-value sentinel proves the env var is restored on the
    success path; the production helper's failure-path restoration is
    identical (same `try/finally`)."""
    scratch = tmp_path / "scratch.db"
    sentinel = "sqlite:///prior-value-should-be-restored"
    prior = os.environ.get("DATABASE_URL")
    os.environ["DATABASE_URL"] = sentinel
    try:
        assert _roundtrip_inproc(str(scratch)) == 0
        assert os.environ.get("DATABASE_URL") == sentinel
    finally:
        if prior is None:
            os.environ.pop("DATABASE_URL", None)
        else:
            os.environ["DATABASE_URL"] = prior
