"""Integration tests for scripts/dev/migrate.py.

These tests shell out to a real `alembic` against a temp sqlite DB. They are
the first `test_*.py` under `scripts/`; pytest discovers them via the
`scripts` entry in `pyproject.toml`'s `testpaths`.
"""

from __future__ import annotations

import os
import sqlite3
import subprocess
from pathlib import Path

import pytest

from scripts.dev import migrate
from scripts.dev_cli import CLIRunner

PROJECT_ROOT = Path(__file__).resolve().parents[2]
VERSIONS_DIR = PROJECT_ROOT / "alembic" / "versions"


@pytest.fixture
def runner() -> CLIRunner:
    return CLIRunner()


@pytest.fixture
def temp_db(tmp_path, monkeypatch) -> Path:
    """Point DATABASE_URL at a fresh per-test sqlite DB."""
    db = tmp_path / "test.db"
    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{db}")
    return db


@pytest.fixture(autouse=True)
def clean_new_revision_files():
    """Remove any new files autogenerated under alembic/versions during a test.

    Snapshots the directory at setup; at teardown deletes anything new so a
    failed test can't leave a stray revision behind.
    """
    before = {p.name for p in VERSIONS_DIR.iterdir() if p.is_file()}
    yield
    after = {p.name for p in VERSIONS_DIR.iterdir() if p.is_file()}
    for name in after - before:
        (VERSIONS_DIR / name).unlink()


def _alembic_head_revision() -> str:
    """Return the head revision id from `alembic heads` (host mode)."""
    out = subprocess.run(
        ["alembic", "-c", "config/alembic.ini", "heads"],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    # Output looks like "abc123 (head)\n"; take the first token of the first line.
    line = next(line for line in out.stdout.splitlines() if line.strip())
    return line.split()[0]


def _db_version(db_path: Path) -> str | None:
    """Read the current alembic_version from a sqlite DB, or None if absent."""
    if not db_path.exists():
        return None
    conn = sqlite3.connect(db_path)
    try:
        rows = conn.execute(
            "SELECT name FROM sqlite_master "
            "WHERE type='table' AND name='alembic_version'"
        ).fetchall()
        if not rows:
            return None
        row = conn.execute("SELECT version_num FROM alembic_version").fetchone()
        return row[0] if row else None
    finally:
        conn.close()


def test_up_applies_to_head(runner: CLIRunner, temp_db: Path):
    rc = migrate.up(runner)
    assert rc == 0
    assert _db_version(temp_db) == _alembic_head_revision()


def test_down_one_step_then_up(runner: CLIRunner, temp_db: Path):
    assert migrate.up(runner) == 0
    head = _alembic_head_revision()
    assert _db_version(temp_db) == head

    assert migrate.down(runner, steps=1) == 0
    assert _db_version(temp_db) != head

    assert migrate.up(runner) == 0
    assert _db_version(temp_db) == head


def test_down_multi_step(runner: CLIRunner, temp_db: Path):
    assert migrate.up(runner) == 0
    head = _db_version(temp_db)

    assert migrate.down(runner, steps=2) == 0
    after = _db_version(temp_db)
    assert after != head


def test_generate_creates_revision_file(runner: CLIRunner, temp_db: Path):
    # Autogenerate refuses unless the DB is already at head.
    assert migrate.up(runner) == 0

    before = {p.name for p in VERSIONS_DIR.iterdir() if p.is_file()}
    rc = migrate.generate(runner, "test_step_b_revision")
    assert rc == 0
    after = {p.name for p in VERSIONS_DIR.iterdir() if p.is_file()}
    new_files = after - before
    assert len(new_files) == 1, f"expected one new revision file, got {new_files}"
    # Sanity: the new file's name encodes the message slug.
    assert "test_step_b_revision" in next(iter(new_files))


def test_roundtrip_uses_explicit_scratch(runner: CLIRunner, tmp_path: Path):
    scratch = tmp_path / "scratch.db"
    dev_db = PROJECT_ROOT / "data" / "aimagain.db"
    dev_mtime = dev_db.stat().st_mtime if dev_db.exists() else None

    rc = migrate.roundtrip(runner, scratch_path=str(scratch))
    assert rc == 0
    assert not scratch.exists(), "scratch DB should be removed on success"

    if dev_mtime is not None:
        assert (
            dev_db.stat().st_mtime == dev_mtime
        ), "roundtrip must not touch data/aimagain.db"


def test_roundtrip_default_scratch(runner: CLIRunner):
    default_path = Path(migrate.DEFAULT_ROUNDTRIP_SCRATCH)
    if default_path.exists():
        default_path.unlink()

    try:
        rc = migrate.roundtrip(runner)
        assert rc == 0
        assert (
            not default_path.exists()
        ), "default scratch DB should be removed on success"
    finally:
        if default_path.exists():
            default_path.unlink()


def test_roundtrip_restores_database_url(runner: CLIRunner, tmp_path: Path):
    """roundtrip must restore the prior DATABASE_URL even on failure."""
    scratch = tmp_path / "scratch.db"
    sentinel = "sqlite:///prior-value-should-be-restored"
    prior = os.environ.get("DATABASE_URL")
    os.environ["DATABASE_URL"] = sentinel
    try:
        assert migrate.roundtrip(runner, scratch_path=str(scratch)) == 0
        assert os.environ.get("DATABASE_URL") == sentinel
    finally:
        if prior is None:
            os.environ.pop("DATABASE_URL", None)
        else:
            os.environ["DATABASE_URL"] = prior
