name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual trigger

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deployment/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy deployment files to droplet (manual SCP)
        run: |
          # Create temporary SSH key file from secret
          echo "${{ secrets.DROPLET_SSH_KEY }}" > /tmp/droplet_ssh_key
          chmod 600 /tmp/droplet_ssh_key

          # Set environment variables for the script
          export DROPLET_HOST="${{ secrets.DROPLET_HOST }}"
          export DROPLET_USERNAME="${{ secrets.DROPLET_USERNAME }}"
          export DROPLET_SSH_KEY_PATH="/tmp/droplet_ssh_key"

          # Run the manual copy script
          ./deployment/scripts/deploy-copy-files.sh

          # Clean up temporary key file
          rm -f /tmp/droplet_ssh_key

      - name: Run deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /opt/aimagain/deployment
            chmod +x deploy.sh cleanup-docker.sh
            ./deploy.sh
