name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch: # Allow manual runs

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PYTHON_VERSION: '3.11'
  DATABASE_URL: sqlite+aiosqlite:///./test.db
  SECRET: test-secret-key-for-ci-only
  ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: 60
  ONLINE_TIMEOUT_MINUTES: 10

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-
      - name: Install Playwright browsers
        run: |
          playwright install --with-deps
      - name: Create test database
        run: |
          alembic upgrade head

      - name: Run pytest
        run: pytest -v --tb=short

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pathspec  # For title case checker

      - name: Run linting
        run: |
          black --check .
          isort --check-only .

      - name: Run title case check
        run: python scripts/dev/title_case_check.py --check-only

  docker-health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image for testing
        run: |
          docker build -f ./deployment/docker/Dockerfile -t test-image .

      - name: Test Docker image health
        run: |
          # Start container in background
          docker run -d --name test-container -p 8000:8000 \
            -e SECRET=test-secret \
            -e ACCESS_TOKEN_EXPIRE_MINUTES=30 \
            -e ONLINE_TIMEOUT_MINUTES=5 \
            test-image

          # Wait for container to start
          sleep 10

          # Health check - verify the app responds
          curl -f http://localhost:8000/docs/ || exit 1

          # Cleanup
          docker stop test-container
          docker rm test-container
